### ISSUE TITLE
Cannot translate double interface overriding.

### ISSUE THREAD

**Issue by michaelcheers** [bridgedotnet/Bridge#1393]
### Expected

Compile fine.

### Actual
```
C# to JavaScript Compilation Failed

System.Exception: Cannot translate interface (Demo.MyInterface) member '[Method Demo.Derived.Method():System.Void]' in 'Demo.Derived' due name conflicts. Please rename methods or refactor your code
   at Bridge.Contract.OverloadsCollection.GetOverloadName(IMember definition)
   at Bridge.Contract.OverloadsCollection.GetOverloadName()
   at Bridge.Translator.VisitorMethodBlock.VisitMethodDeclaration(MethodDeclaration methodDeclaration)
   at Bridge.Translator.VisitorMethodBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.Emitter.VisitMethodDeclaration(MethodDeclaration methodDeclaration)
   at Bridge.Translator.MethodBlock.EmitMethodsGroup(List`1 group)
   at Bridge.Translator.MethodBlock.EmitMethods(Dictionary`2 methods, Dictionary`2 properties, Dictionary`2 operators)
   at Bridge.Translator.MethodBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.ClassBlock.EmitInstantiableBlock()
   at Bridge.Translator.ClassBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.EmitBlock.DoEmit()
   at Bridge.Translator.AbstractEmitterBlock.Emit()
   at Bridge.Translator.Emitter.Emit()
   at Bridge.Translator.Translator.Translate()
   at Live.LiveTranslator.Translate(String& output)
   at Live.TranslateHandler.Translate(String csCode)
```
### Steps To Reproduce
[Live Bridge](http://live.bridge.net/#0599f3df162ac4e885c9426b2fd01bb2)
[Dot Net Fiddle](https://dotnetfiddle.net/phYruv)
```csharp
public interface MyInterface {
  void Method();
}
public class Base {
  public void Method() { }
}
public class Derived : Base, MyInterface { public void Method (){} }

public class App
{
    [Ready]
	public static void Main ()
	{
	}
}
```

**Comment by vladsch** [comment]
It is the same issue as
#1025 and #1307

See comment #1025 (comment)

**Comment by michaelcheers** [comment]
@vladsch, no it's not it is not using explicit interface members.

**Comment by vladsch** [comment]
It is the same limitation when Bridge find methods which must be translated with the same javascript name

**Comment by LeonidVeriga** [comment]
#1025 has been fixed.

**Comment by kcudnik** [comment]
@michaelcheers: Take a look here [Live](http://live.bridge.net/#da813d366481d852abeb4b11f2252ca3) this works as expected, not sure if this solves your problem

**Comment by vladsch** [comment]
@kcudnik your live sample doesn't use interface (i mean that no classes which implement interface)

**Comment by kcudnik** [comment]
Stupid me, forgot to add that interface to base class, but with that problem still exists :(

**Comment by vladsch** [comment]
Yes, Live uses 1.14 version (we update Live after each release)
The fix is merged with master and will be included to next release
