### ISSUE TITLE
Complex Dictionary-Key gets serialized to [object Object]

### ISSUE THREAD

**Issue by mRy0** [bridgedotnet/Bridge#3376]
Hello,

I am using a dictionary with an object as key for accessing data with multiple different indexes. If I serialize this dictionary to JSONthe key gets serialized to [object, object] and can,t get deserialized.

Deck.NET Example
https://deck.net/56b2be737ccaf5bf0a8153fa5b170324

Code

```csharp
public class Program
{
    private class ComplexKey{
        public string Foo { set; get; }
        public string Bar { set; get; }
                
        public ComplexKey(string foo, string bar){
            Foo = foo;
            Bar = bar;
        }
        
         public override bool Equals(object obj)
        {
            return (obj is ComplexKey) && (((ComplexKey)obj).Foo.Equals(this.Foo)) &&
                    (((ComplexKey)obj).Bar.Equals(this.Bar));
        }

        protected bool Equals(ComplexKey other)
        {
            return string.Equals(Foo, other.Foo) && string.Equals(Bar, other.Bar);
        }

        public override int GetHashCode()
        {
            unchecked
            {
                return ((Foo != null ? Foo.GetHashCode() : 0) * 397) ^ (Bar != null ? Bar.GetHashCode() : 0);
            }
        }
    }
    
    
    public static void Main()
    {
        //create dictionary
        var testDic = new Dictionary<ComplexKey, string>();
        
        //add some data
        testDic.Add(new ComplexKey("Hello", "World"), "some data");
        testDic.Add(new ComplexKey("World", "Hello"), "some other data");
        
        //test access
        Console.WriteLine("access test with key: " + testDic[new ComplexKey("Hello", "World")]);
        
        //serialize
        var json = Newtonsoft.Json.JsonConvert.SerializeObject(testDic);
        Console.WriteLine("TestJson: \n\r" + json);
        //deserialize        
        var testDesDic = Newtonsoft.Json.JsonConvert.DeserializeObject<Dictionary<ComplexKey, string>>(json);
        //print back data
        Console.WriteLine("access test with key: " + testDesDic[new ComplexKey("Hello", "World")]);        
    }
}
```

**Comment by vladsch** [comment]
It is already fixed.
https://github.com/bridgedotnet/Bridge.Newtonsoft.Json/issues/74

**Comment by geoffreymcgill** [comment]
The dev.deck.net instance still needs to be updated with **Bridge.Newtonsoft.Json**, but we'll get that updated today so testing with the new fix will be possible. 

https://dev.deck.net/56b2be737ccaf5bf0a8153fa5b170324

The new releases are scheduled for [2018-01-22](https://github.com/bridgedotnet/Bridge/milestone/52).

**Comment by mRy0** [comment]
Okay Tranks, 
I have only searched in this repository.

**Comment by geoffreymcgill** [comment]
Looks like this is a new issue. We are investigating.

**Comment by fabriciomurta** [comment]
The code also breaks on .NET althoug, that's also during deserialization. The serialization result does not match and the [Object object] is still an issue: https://dotnetfiddle.net/YIYCew

Deck with the "assert-ish" code: https://deck.net/a1b44a842160f54f6d93f11edf93d186

**Comment by fabriciomurta** [comment]
Fixed and merged (github didn't catch the merge). The fix will make it to the next Bridge release (see attached milestone).
